import type { WidgetTemplate } from './types';

const IMG = {
  digicamPink_small: require('../../assets/widget-templates/digicam-pink/small.png'),
  digicamPink_large: require('../../assets/widget-templates/digicam-pink/large.png'),
  ginghamBowBlue_medium: require('../../assets/widget-templates/gingham-bow-blue/medium.png'),
  denimFlowers_medium: require('../../assets/widget-templates/denim-flowers/medium.png'),
  digicamFilm_small: require('../../assets/widget-templates/digicam-film/small.png'),
  digicamFilm_large: require('../../assets/widget-templates/digicam-film/large.png'),
  pinkScrapCard_small: require('../../assets/widget-templates/pink-scrap-card/small.png'),
  pinkScrapCard_large: require('../../assets/widget-templates/pink-scrap-card/large.png'),
  ginghamPearl_medium: require('../../assets/widget-templates/gingham-pearl/medium.png'),
  digicamLavender_small: require('../../assets/widget-templates/digicam-lavender/small.png'),
  digicamLavender_large: require('../../assets/widget-templates/digicam-lavender/large.png'),
  waveScrapbook_small: require('../../assets/widget-templates/wave-scrapbook/small.png'),
  waveScrapbook_large: require('../../assets/widget-templates/wave-scrapbook/large.png'),
  starrySky_small: require('../../assets/widget-templates/starry-sky/small.png'),
  starrySky_large: require('../../assets/widget-templates/starry-sky/large.png'),
  lockers_small: require('../../assets/widget-templates/lockers/small.png'),
  lockers_large: require('../../assets/widget-templates/lockers/large.png'),
  clipboardPenco_small: require('../../assets/widget-templates/clipboard-penco/small.png'),
  clipboardPenco_large: require('../../assets/widget-templates/clipboard-penco/large.png'),
  archiveGingham_small: require('../../assets/widget-templates/archive-gingham/small.png'),
  archiveGingham_large: require('../../assets/widget-templates/archive-gingham/large.png'),
  ginghamCenter_small: require('../../assets/widget-templates/gingham-center/small.png'),
  ginghamCenter_large: require('../../assets/widget-templates/gingham-center/large.png'),
  denimFrame_small: require('../../assets/widget-templates/denim-frame/small.png'),
  denimFrame_large: require('../../assets/widget-templates/denim-frame/large.png'),
  gridPaper_small: require('../../assets/widget-templates/grid-paper/small.png'),
  gridPaper_large: require('../../assets/widget-templates/grid-paper/large.png'),
  picnicTable_small: require('../../assets/widget-templates/picnic-table/small.png'),
  picnicTable_large: require('../../assets/widget-templates/picnic-table/large.png'),
  digicamClassic_small: require('../../assets/widget-templates/digicam-classic/small.png'),
  digicamClassic_large: require('../../assets/widget-templates/digicam-classic/large.png'),
  digicamGreen_small: require('../../assets/widget-templates/digicam-green/small.png'),
  digicamGreen_large: require('../../assets/widget-templates/digicam-green/large.png'),
  digicamYellow_small: require('../../assets/widget-templates/digicam-yellow/small.png'),
  digicamYellow_large: require('../../assets/widget-templates/digicam-yellow/large.png'),
  doodleFlowers_medium: require('../../assets/widget-templates/doodle-flowers/medium.png'),
  ribbonBows_medium: require('../../assets/widget-templates/ribbon-bows/medium.png'),
  dreamyStars_medium: require('../../assets/widget-templates/dreamy-stars/medium.png'),
  butterflyGlow_medium: require('../../assets/widget-templates/butterfly-glow/medium.png'),
  coastalHappen_medium: require('../../assets/widget-templates/coastal-happen/medium.png'),
  meadowTime_small: require('../../assets/widget-templates/meadow-time/small.png'),
  meadowTime_large: require('../../assets/widget-templates/meadow-time/large.png'),
  reminderGingham_medium: require('../../assets/widget-templates/reminder-gingham/medium.png'),
  fishOnce_medium: require('../../assets/widget-templates/fish-once/medium.png'),
  easeJournal_medium: require('../../assets/widget-templates/ease-journal/medium.png'),
  studyGingham_medium: require('../../assets/widget-templates/study-gingham/medium.png'),
  quoteGoodThings_small: require('../../assets/widget-templates/quote-good-things/small.png'),
  quoteGoodThings_large: require('../../assets/widget-templates/quote-good-things/large.png'),
  quoteBeKind_small: require('../../assets/widget-templates/quote-be-kind/small.png'),
  quoteBeKind_large: require('../../assets/widget-templates/quote-be-kind/large.png'),
  quoteSmallSteps_small: require('../../assets/widget-templates/quote-small-steps/small.png'),
  quoteSmallSteps_large: require('../../assets/widget-templates/quote-small-steps/large.png'),
  quoteWorksOut_small: require('../../assets/widget-templates/quote-works-out/small.png'),
  quoteWorksOut_large: require('../../assets/widget-templates/quote-works-out/large.png'),
  quoteFavorite_small: require('../../assets/widget-templates/quote-favorite/small.png'),
  quoteFavorite_large: require('../../assets/widget-templates/quote-favorite/large.png'),
  iosReminder_small: require('../../assets/widget-templates/ios-reminder/small.png'),
  iosReminder_large: require('../../assets/widget-templates/ios-reminder/large.png'),
  polaroidStack_small: require('../../assets/widget-templates/polaroid-stack/small.png'),
  polaroidStack_large: require('../../assets/widget-templates/polaroid-stack/large.png'),
  pastelDoodles_medium: require('../../assets/widget-templates/pastel-doodles/medium.png'),
  quoteBreathe_small: require('../../assets/widget-templates/quote-breathe/small.png'),
  quoteBreathe_large: require('../../assets/widget-templates/quote-breathe/large.png'),
  quoteSelfLove_small: require('../../assets/widget-templates/quote-self-love/small.png'),
  quoteSelfLove_large: require('../../assets/widget-templates/quote-self-love/large.png'),
  tapePhotos_small: require('../../assets/widget-templates/tape-photos/small.png'),
  tapePhotos_large: require('../../assets/widget-templates/tape-photos/large.png'),
  quoteYouGotThis_small: require('../../assets/widget-templates/quote-you-got-this/small.png'),
  quoteYouGotThis_large: require('../../assets/widget-templates/quote-you-got-this/large.png'),
  heartFrame_small: require('../../assets/widget-templates/heart-frame/small.png'),
  heartFrame_large: require('../../assets/widget-templates/heart-frame/large.png'),
  cloudSoft_small: require('../../assets/widget-templates/cloud-soft/small.png'),
  cloudSoft_large: require('../../assets/widget-templates/cloud-soft/large.png'),
} as const;

export const WIDGET_TEMPLATES: WidgetTemplate[] = [
  {
    id: "digicam-pink",
    name: "Pink digicam",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.digicamPink_small,
      large: IMG.digicamPink_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "gingham-bow-blue",
    name: "Blue gingham bow",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.ginghamBowBlue_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "denim-flowers",
    name: "Denim flowers",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.denimFlowers_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "digicam-film",
    name: "Film digicam",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.digicamFilm_small,
      large: IMG.digicamFilm_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "pink-scrap-card",
    name: "Pink scrap card",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.pinkScrapCard_small,
      large: IMG.pinkScrapCard_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "gingham-pearl",
    name: "Pearl gingham",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.ginghamPearl_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "digicam-lavender",
    name: "Lavender digicam",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.digicamLavender_small,
      large: IMG.digicamLavender_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "wave-scrapbook",
    name: "Wave journal",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.waveScrapbook_small,
      large: IMG.waveScrapbook_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "starry-sky",
    name: "Starry sky",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.starrySky_small,
      large: IMG.starrySky_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "lockers",
    name: "Lockers",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.lockers_small,
      large: IMG.lockers_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "clipboard-penco",
    name: "Clipboard",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.clipboardPenco_small,
      large: IMG.clipboardPenco_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "archive-gingham",
    name: "Archive tag",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.archiveGingham_small,
      large: IMG.archiveGingham_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "gingham-center",
    name: "Gingham center",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.ginghamCenter_small,
      large: IMG.ginghamCenter_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "denim-frame",
    name: "Denim frame",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.denimFrame_small,
      large: IMG.denimFrame_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "grid-paper",
    name: "Grid notes",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.gridPaper_small,
      large: IMG.gridPaper_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "picnic-table",
    name: "Picnic",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.picnicTable_small,
      large: IMG.picnicTable_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "digicam-classic",
    name: "Classic digicam",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.digicamClassic_small,
      large: IMG.digicamClassic_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "digicam-green",
    name: "Green digicam",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.digicamGreen_small,
      large: IMG.digicamGreen_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "digicam-yellow",
    name: "Yellow digicam",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.digicamYellow_small,
      large: IMG.digicamYellow_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "doodle-flowers",
    name: "Doodle flowers",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.doodleFlowers_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "ribbon-bows",
    name: "Ribbon bows",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.ribbonBows_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "dreamy-stars",
    name: "Dreamy stars",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.dreamyStars_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "butterfly-glow",
    name: "Butterfly glow",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.butterflyGlow_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "coastal-happen",
    name: "Make it happen",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.coastalHappen_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "meadow-time",
    name: "Good things take time",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.meadowTime_small,
      large: IMG.meadowTime_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "reminder-gingham",
    name: "Reminder card",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.reminderGingham_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "fish-once",
    name: "Only once",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.fishOnce_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "ease-journal",
    name: "Feel ease",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.easeJournal_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "study-gingham",
    name: "Study now",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.studyGingham_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "quote-good-things",
    name: "Good things",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.quoteGoodThings_small,
      large: IMG.quoteGoodThings_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "quote-be-kind",
    name: "Be kind",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.quoteBeKind_small,
      large: IMG.quoteBeKind_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "quote-small-steps",
    name: "Small steps",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.quoteSmallSteps_small,
      large: IMG.quoteSmallSteps_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "quote-works-out",
    name: "Works out",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.quoteWorksOut_small,
      large: IMG.quoteWorksOut_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "quote-favorite",
    name: "Favorite things",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.quoteFavorite_small,
      large: IMG.quoteFavorite_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "ios-reminder",
    name: "Proud reminder",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.iosReminder_small,
      large: IMG.iosReminder_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "polaroid-stack",
    name: "Polaroid stack",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.polaroidStack_small,
      large: IMG.polaroidStack_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "pastel-doodles",
    name: "Pastel doodles",
    kind: "full",
    families: ["medium"],
    images: {
      medium: IMG.pastelDoodles_medium,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
  {
    id: "quote-breathe",
    name: "Breathe",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.quoteBreathe_small,
      large: IMG.quoteBreathe_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "quote-self-love",
    name: "Self love",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.quoteSelfLove_small,
      large: IMG.quoteSelfLove_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "tape-photos",
    name: "Tape photos",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.tapePhotos_small,
      large: IMG.tapePhotos_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "quote-you-got-this",
    name: "You got this",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.quoteYouGotThis_small,
      large: IMG.quoteYouGotThis_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "heart-frame",
    name: "Heart frame",
    kind: "cutout",
    families: ["small","large"],
    images: {
      small: IMG.heartFrame_small,
      large: IMG.heartFrame_large,
    },
    placementMode: 'free',
    maxStickers: 10,
    captionEnabled: true,
  },
  {
    id: "cloud-soft",
    name: "Soft clouds",
    kind: "full",
    families: ["small","large"],
    images: {
      small: IMG.cloudSoft_small,
      large: IMG.cloudSoft_large,
    },
    placementMode: 'free',
    maxStickers: 12,
    captionEnabled: true,
  },
];

export function getWidgetTemplate(id: string): WidgetTemplate | undefined {
  return WIDGET_TEMPLATES.find(t => t.id === id);
}

export function templateImage(template: WidgetTemplate, family: import('./widgetSizes').WidgetFamily) {
  return template.images[family] ?? template.images[template.families[0]];
}

export function templatesForFamily(family: import('./widgetSizes').WidgetFamily): WidgetTemplate[] {
  return WIDGET_TEMPLATES.filter(t => {
    if (!t.families.includes(family)) return false;
    if (family === 'medium' && t.kind === 'cutout') return false;
    if ((family === 'small' || family === 'large') && t.families.length === 1 && t.families[0] === 'medium') {
      return false;
    }
    return true;
  });
}
