import { Platform, StyleSheet } from 'react-native';

export const hubPageStyles = StyleSheet.create({
  root: { flex: 1 },
  hobbyPill: { marginTop: 10, alignSelf: 'flex-start', borderRadius: 999, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 },
  proBadge: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 22 },
  proBadgeText: { color: '#FFF', fontSize: 13, fontWeight: '900' },
  upgradeBtn: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 22, borderWidth: 1 },
  sectionHead: { paddingHorizontal: 22, paddingTop: 16, paddingBottom: 6 },
  sectionTitle: { fontSize: 9, fontWeight: '900', letterSpacing: 4, textTransform: 'none' },
  galleryHint: { fontSize: 11, fontWeight: '600', lineHeight: 16, marginTop: 4 },
  proStrip: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,0,0,0.78)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  proStripTxt: { color: '#FFF', fontSize: 10, fontWeight: '900', letterSpacing: 0.5 },
  section: { paddingHorizontal: 16, paddingBottom: 8 },
  letterOuter: {
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 8,
    borderRadius: 16,
    overflow: 'hidden',
    minHeight: 220,
    borderWidth: 1,
  },
  letterPanel: {
    margin: 14,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 251, 245, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(74, 55, 40, 0.22)',
  },
  letterMeta: { fontSize: 10, fontWeight: '900', letterSpacing: 3, marginBottom: 12, color: '#6b5344' },
  letterBody: {
    fontFamily: Platform.OS === 'ios' ? 'American Typewriter' : 'monospace',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '500',
    color: '#3d2914',
  },
  proLooksRail: {
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 6,
    borderRadius: 22,
    borderWidth: 1,
    overflow: 'hidden',
    paddingBottom: 4,
  },
  klFooter: {
    marginHorizontal: 16,
    marginTop: 20,
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    minHeight: 200,
    borderWidth: 1,
  },
  klFooterTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 2,
    textAlign: 'center',
    textShadowColor: '#000000',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 14,
  },
  klFooterSub: {
    color: 'rgba(255,255,255,0.96)',
    fontSize: 13,
    lineHeight: 21,
    textAlign: 'center',
    marginTop: 10,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'American Typewriter' : 'monospace',
    textShadowColor: '#000000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
  },
  klLink: {
    color: '#FFFACD',
    fontSize: 12,
    fontWeight: '900',
    textDecorationLine: 'underline',
    textShadowColor: '#000000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
});
